### PR TITLE
Charts update

### PR DESCRIPTION
**Pull request by dhananjay12**

### CODE REVIEW

**Review by torrespro — CHANGES_REQUESTED** [review]
Could you upgrade the diagram to remove Eureka from there?

**Comment by dhananjay12** [comment]
Image updated

**Review by torrespro — APPROVED** [review]

**Comment by torrespro** [comment]
Change the image also please, not only the Puml file. And also if you can check what is going with the github action that checks the lint of the chart, not urgent but used to work

**Comment by dhananjay12** [comment]
I updated the image only - https://github.com/Backbase/helm-k8s-local/blob/charts-update/bb-local-kubernetes.png
The puml file was already up to date

**Review by psplinakis — APPROVED** [review]

**Pull request merged**
